name: Build Unity package
on: workflow_dispatch
jobs:
  linux-x64:
    name: Linux x64
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: make -f Unix/Makefile
    # macos:
    #     name: macOS
    #     runs-on: macos-latest
    # windows:
    #     name: Windows
    #     runs-on: windows-latest